### ISSUE TITLE
Cannot get medium user: Access token required

### ISSUE THREAD

**Issue by BenediktHoelker** [andremueller/md-publisher#1]
Hi Andre,

thanks a lot for your efforts and the `md-publisher` - it's exactly what I was looking for. Unfortunately I am getting an error 

`FATA[0000] Cannot get medium user: medium: An access token is required. (6000)` on both Windows an MacOS even though I provided a medium Access token. I've tried it with the Access token defined in a config file and via the command line. Is it just me having difficulties handling the program or is there a problem with the tool? 

Best regards 
Benedikt

**Comment by andremueller** [comment]
Hi Benedikt,

thanks alot for checking my tool!
I tried it using a config file - at my place the login to medium works. Did you provide the token on the command line or place it to a config file (defaulting to `$HOME/.config/md-publisher/md-publisher.conf`)?

Regards

André

**Comment by andremueller** [comment]
After a bit of digging ....

Medium seems not to accept your token. As far as I remember the token is only valid, if you did at least publish one article within Medium.
Did you try to create a fresh "Integration Token" within Medium https://medium.com/me/settings? Really double check your token.
In the config file the token must be surrounded by double ticks not containing any other whitespaces. Something like
```
MediumAccessToken="22babe17171717...."
```
I found an article on stackoverflow https://stackoverflow.com/questions/54457396/medium-applications-for-api-access-no-longer-available-to-free-users
So probably the API is only available for payed accounts (I don't know which one you have). Did you have any other application using Medium API running?

According to
https://github.com/Medium/medium-api-docs/blob/master/README.md
you need to write an eMail to the Medium support to activate your integration tokens yourfriends@medium.com

**Comment by BenediktHoelker** [comment]
Hey Andre,

thanks for your super-quick response and sorry that it took me so long to answer. I reached out to the Medium-team and asked them to activate the token. I will let you know, as soon as I get an answer.

By the way I double-checked my configuration and checked both ways, providing it via the command line option as _--medium-token_ and providing it via the config file - I am still getting the error of 'Cannot get medium user: medium: An access token is required. (6000)'.

Thanks for your efforts so far!
Benedikt

**Comment by krocodl** [comment]
Dear Andre,

I have the same issue - 6000  error. 
But it looks like this issue is not related to the paid nature of my account. 
At a minimum, I can use it with https://github.com/maximegel/blogster and the article can be published.

BTW, I have another question: Is it possible by your tool to publish the documents with multiple included lists?
Something like

```
<ul>
<li>First item</li>
<li>Second item</li>
<li>Third item
<ul>
<li>Indented item</li>
<li>Indented item</li>
</ul>
</li>
<li>Fourth item</li>
</ul> 
```



With regards,
VIctor Alekseev

**Comment by krocodl** [comment]
The reason:
	client := medium.NewClientWithAccessToken(config.MediumAccessToken)
So, key MediumAccessToken has to be defined in the config file globally, not under [medium] section

**Comment by krocodl** [comment]
The sample with multiple included lists does not work ;(

**Comment by andremueller** [comment]
Dear Victor,

you are right! Nested lists do not work. However, when using HTML (see my new upload example on the master branch) this seems to be a unsupported feature in medium.com ....
Documentation was updated. Indeed, the `[medium]` section header in the config file should just be removed. Updated doc accordingly.

Regards

Andre

**Comment by andremueller** [comment]
@krocodl Could you try publishing again with the medium key in the conf file without that [medium] section? At my place it works without problems. Would be interesting what is behind this magic error from the medium API.

**Comment by krocodl** [comment]
@andremueller I already tried yesterday - without [medium] section all works properly
