### ISSUE TITLE
How to edit a post?

### ISSUE THREAD

**Issue by jbis9051** [andremueller/md-publisher#23]
Is there a way to edit a post that's already published?

**Comment by andremueller** [comment]
You currently can only publish an article as a new draft. As far as I know, the Medium API does not allow to update a post. Usually I publish the piece as a draft and fix small formatting issues within the medium web editor before going live.

**Comment by jbis9051** [comment]
Well then mediums API is garbage haha. Maybe we can tap into something unofficial.
