### ISSUE TITLE
Unable to Install/ Build Package

### ISSUE THREAD

**Issue by dvdmtw98** [andremueller/md-publisher#51]
When I try to install md-publisher using `go get` i get error saying that this command is only supported in modules instead use the `go install` command when I do `go install github.com/andremueller/md-publisher@latest` I can see packages getting download but after its done if I type md-publisher or md-publisher help I get command not found.

I tried to clone the repository and from within the repository run `go get github.com/andremueller/md-publisher` it again shows some packages getting download but when I list the files in the directory I do not see any binary file. Tried running the build.sh command as well but getting the same result. 

I have tried the same from a Docker Container as well as from a Ubuntu VM but getting the same issue. Can you help me I am not sure what am I going wrong using go version 1.19.4

**Comment by dvdmtw98** [comment]
On further debugging it looks like running `go run main.go` from the repository does launch the tool but it is enable to read the config file even though it exists

**Comment by dvdmtw98** [comment]
Okay so using the `go build` command I was able to generate the executable but it keeps saying config cannot be found but the config does exist at the specified path. As the steps for installing and configuring this package changed ?

**Comment by dvdmtw98** [comment]
After generating a new token I am now able to successfully upload the html file to my account but it is still showing the error config file not found

**Comment by andremueller** [comment]
Hmm. Strange. I really did not change anything the last time (besides some updates of the packages by the depandabot). What operating system do you use, and where did you put your config file?

**Comment by andremueller** [comment]
Regarding your installation issue: I update the README according to that (go changed that a bit)

**Comment by dvdmtw98** [comment]
> Hmm. Strange. I really did not change anything the last time (besides some updates of the packages by the depandabot). What operating system do you use, and where did you put your config file?

Using the build command I was able to compile the executable and using that I was able to publish the article but not sure why I was getting the error even though it worked. I was trying them from a Debian Dev Container and Ubuntu VM and the config file was in the location mentioned in the README.
